---
abstract: 'generate simple text tables from 2D arrays'
author:
  - 'Creighton Higgins <chiggins@chiggins.com>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Table-Tiny
requires:
  Carp: '0'
  Exporter: '0'
  Ref::Util: '0'
  parent: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/neilb/Text-Table-Tiny/issues
  homepage: https://github.com/neilb/Text-Table-Tiny
  repository: https://github.com/neilb/Text-Table-Tiny.git
version: 0.05_03
x_generated_by_perl: v5.28.2
x_serialization_backend: 'YAML::Tiny version 1.73'
